---
Name: focuspoint
After:
  - 'framework/*'
---

SilverStripe\Assets\Image:
  extensions:
    - Jonom\FocusPointImage

SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - Jonom\ImageFormFactoryExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    'jonom/focuspoint: client/js/FocusPointField.js':
  extra_requirements_css:
    'jonom/focuspoint: client/css/FocusPointField.css':
